package controller;


import java.sql.SQLException;

import model.Demon;
import model.Map;



public interface IController {

	/**
	 * Initiates the whole game
	 * @throws SQLException
	 */
	public void start() throws SQLException; 	
	
	/**
	 * Allows the player to play on 1 map
	 * If the player wins, the next map is called
	 * @param mapchoice
	 * @throws SQLException
	 */
	public void play(String mapchoice) throws SQLException;
	
	/**
	 * Generates the object "map" through the use of a DAO
	 * @param mapString
	 * @return
	 */
	public Map createMap(String mapString);	
	
	/**
	 * Checks if the movement generated by "updateModel()" is possible, and if it ends the game.
	 * @param demon
	 * @param i
	 * @return
	 */
	public boolean checkAI(Demon demon ,int i);
	
	/**
	 * prints the logical model (Map.grid) on the frame's panel
	 */
	public void display();	
	
	/**
	 * checks the last key pressed by the user kept in the "lastOrder" enum in frame.
	 */
	public void checkMovement();
	
	/**
	 *Generates random movements for the AIs 
	 */
	public void updateModel();	
	
	/**
	 *Displays the "Lost" screen 
	 */
	public void lost();
	
	/**
	 * uses an instance of the "Console" class from the View Package to allow the user to choose a map
	 * @return
	 */
	public String chooseMap();
	
	/**
	 *Main game loop, periodically displays the map and updates the model 
	 */
	public void loop();
	
	/**
	 * Displays the "you won" messages and total score
	 */
	public void won();										
	
}
